### PR TITLE
Dbatiste/minor housekeeping

### PR DESCRIPTION
**Pull request by dbatiste**
* update ignore list
* add landing page

### CODE REVIEW

**Comment by dbatiste** [comment]
@margaree : i notice the polymer range in the bower dependencies, but there is no variant so it is not possible to test this demo with polymer 1 & 2.  is this component supposed to be for polymer 1 and 2, or is it strictly 2?  i'll either update the polymer dependency or add the variant depending on your answer... :)

**Comment by margaree** [comment]
It is for 1 & 2. Thanks :)

**Comment by dbatiste** [comment]
Awesome... thanks!

**Comment by dbatiste** [comment]
@margaree : i've updated.  so... with the variant, when you run `polymer serve`, two versions of the component will be hosted... one for running the component with polymer 1, and another for running with polymer 2.  the landing page will give you the option to navigate to one or the other when viewing the demo.  :)

**Pull request merged**
